development:
  adapter: postgresql
  host: db
  database: sample_app
  username: postgres
  password: password1234

test:
  adapter: postgresql
  host: db
  database: sample_app_test
  username: postgres
  password: password1234

